//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dv402 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1dv402.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange erhållet belopp: .
        /// </summary>
        internal static string Cash_Prompt {
            get {
                return ResourceManager.GetString("Cash_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck tangent för ny beräkning - Esc avslutar..
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whops! Du har inte skrivit in en giltig summa..
        /// </summary>
        internal static string Not_A_Number_Error {
            get {
                return ResourceManager.GetString("Not_A_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontant               :{0,10:C}.
        /// </summary>
        internal static string Receipt_Cash {
            get {
                return ResourceManager.GetString("Receipt_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka              :{0,10:C}.
        /// </summary>
        internal static string Receipt_Change {
            get {
                return ResourceManager.GetString("Receipt_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öresavrundning        :{0,10:C}.
        /// </summary>
        internal static string Receipt_Decimals {
            get {
                return ResourceManager.GetString("Receipt_Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att betala            :{0,10:C}.
        /// </summary>
        internal static string Receipt_Pay {
            get {
                return ResourceManager.GetString("Receipt_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVITTO.
        /// </summary>
        internal static string Receipt_Title {
            get {
                return ResourceManager.GetString("Receipt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalt                :{0,10:C}.
        /// </summary>
        internal static string Receipt_Total {
            get {
                return ResourceManager.GetString("Receipt_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whops! {0} är en för liten summa..
        /// </summary>
        internal static string To_Small_Number_Error {
            get {
                return ResourceManager.GetString("To_Small_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange totalsumma: .
        /// </summary>
        internal static string Total_Prompt {
            get {
                return ResourceManager.GetString("Total_Prompt", resourceCulture);
            }
        }
    }
}
